feat: cannot swapoff in hibernation script; need to do it separately using systemd-sleep hook script

diff --git a/roles/power_management/templates/force-hibernate.sh.j2 b/roles/power_management/templates/force-hibernate.sh.j2
--- a/roles/power_management/templates/force-hibernate.sh.j2
+++ b/roles/power_management/templates/force-hibernate.sh.j2
@@ -1,4 +1,6 @@
 #!/usr/bin/env bash
+set -euo pipefail
+
 # Locate the battery device (assumes only one battery)
 BATTERY_DEVICE=$(upower -e | grep -m 1 BAT)
 
@@ -18,8 +20,28 @@ fi
 BATTERY_LEVEL=$(upower -i "$BATTERY_DEVICE" | grep percentage | awk '{print $2}' | sed 's/%//')
 CRITICAL_THRESHOLD={{ battery_critical_level }}
 
-if [ "$BATTERY_LEVEL" -le "$CRITICAL_THRESHOLD" ]; then
-    swapon "{{ hibernate_mapper_device }}"
-    systemctl hibernate --force --ignore-inhibitors
-    swapoff "{{ hibernate_mapper_device }}"
+# Compare battery level with threshold
+if [ "${BATTERY_LEVEL:-0}" -le "${CRITICAL_THRESHOLD:-0}" ]; then
+
+    if swapon "{{ hibernate_mapper_device }}" 2>&1 | logger -t force-hibernate; then
+        logger -t force-hibernate "Hibernation swap enabled successfully: {{ hibernate_mapper_device }}"
+    else
+        if swapoff "{{ hibernate_mapper_device }}" 2>&1 | logger -t force-hibernate; then
+            logger -t force-hibernate "Successfully swapped off {{ hibernate_mapper_device }}"
+            swapon "{{ hibernate_mapper_device }}" 2>&1 | logger -t force-hibernate;
+            logger -t force-hibernate "Hibernate space swapped on back again: {{ hibernate_mapper_device }}"
+        else
+            logger -t force-hibernate "Fallback action failed: swapoff/swapon: {{ hibernate_mapper_device }}"
+        fi
+    fi
+
+    logger -t force-hibernate "Memory usage after swapon:"
+    free -h 2>&1 | logger -t force-hibernate
+    lsblk /dev/mapper/crypthibernate 2>&1 | logger -t force-hibernate
+    swapon --show 2>&1 | logger -t force-hibernate
+
+
+    # The system will hibernate now
+    logger -t force-hibernate "Invoking systemctl hibernate..."
+    systemctl hibernate --force --ignore-inhibitors 2>&1 | logger -t force-hibernate
 fi
